# Generated by Django 5.2.13 on 2026-04-24 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_vehiclelog_car_embedding_vehiclelog_last_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='camera',
            field=models.ForeignKey(blank=True, help_text='الكاميرا المسؤولة عن مراقبة هذا المكان', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_slots', to='parking.camera'),
        ),
        migrations.AddField(
            model_name='vehiclelog',
            name='status',
            field=models.CharField(choices=[('moving', 'Moving'), ('parked', 'Parked'), ('exited', 'Exited')], default='moving', max_length=10),
        ),
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
